libvpx: Autospec creation for update from version 1.12.0 to version 1.13.0
Andrew Salkeld (1):
      Add Neon implementation of vpx_hadamard_32x32

Anton Venema (1):
      Add additional ARM targets for Visual Studio.

Cheng Chen (17):
      L2E: Add control type for the external rate control API
      L2E: Add vp9 GOP decision helper function
      L2E: Return error when GOP model is not set
      L2E: Use bit mask to represent control type
      L2E: send first pass stats before gop decisions
      L2E: rename 'gop_index' to 'gop_global_index'
      L2E: Use libvpx's default q in case of invalid external value
      L2E: Distinguish fixed and active gf_interval
      L2E: Update the description of allow_alt_ref
      L2E: Add more unit tests for GOP API
      Fix VP9 auto level
      L2E: Add target level in GOP unit tests
      Use level defined min gf interval
      L2E: Add gop size and ARF existence to frame info
      L2E: Rework recode decisions for external max frame size and q
      L2E: Add a new interface to control rdmult
      Fix unsigned integer overflow in sse computation

Hirokazu Honda (1):
      vp9/rate_ctrl_rtc: Improve get cyclic refresh data

James Zern (66):
      test/*: normalize use of nullptr
      libs.doxy_template: remove some obsolete variables
      resize_test: add TODO for test failure
      resize_test: add TODO for ResizeTest instantiation for VP9
      vp8e_set_config: setjmp before calling vp8_change_config
      vp9e_set_config: setjmp before calling vp9_change_config
      vp9_change_config: check vp9_alloc_loop_filter return
      vp9,encoder: fix some integer sanitizer warnings
      .gitignore: add android studio / vscode folders
      libs.mk,build/make/Makefile: make test targets ordinary rules
      vp9_cx_iface: set default cpu_used=5 w/CONFIG_REALTIME_ONLY
      vp9_encode_sb_row: remove a branch w/CONFIG_REALTIME_ONLY
      Revert "Fix bug with smaller width bigger size"
      vp8_macros_msa.h: avoid shadowing variables in defines
      vpxenc: fix --disable-loopfilter help alignment
      vpx_int_pro_row_c: add an assert for height
      avg_intrin_{sse2,avg2}: rm dead store in hadamard_8x8
      encode_api_test: quiet static analysis warning
      pp_filter_test: quiet static analysis warning
      avg_intrin_avx2: rm dead store in highbd_hadamard_8x8
      highbd_temporal_filter_sse4: remove unused function params
      y4m_input_fetch_frame: fix ubsan null/zero offset warning
      vp9,decoder_decode: fix ubsan null/zero offset warning
      encode_test_driver: normalize frame_flags type
      vp8_find_near_mvs: fix implicit conversion warnings
      vp8,read_mb_modes_mv: fix implicit conversion warnings
      variance_avx2.c: fix implicit conversion warnings
      vp9_filter_block_plane_non420: fix implicit conversion warnings
      x86: normalize type with _mm_cvtsi128_si32
      vp9_active_[hv]_edge: add missing vpx_clear_system_state
      vp9_cx_iface,encoder_encode: only calc ts when img!=NULL
      configure: add -Wc++{14,17,20}-extensions
      examples/svc_encodeframe.c: rm empty {}s in switch
      simple_encode.cc: clear -Wextra-semi-stmt warnings
      configure: add -Wno-pass-failed for libyuv
      variance_sse2.c: add some missing casts
      load_unaligned_u32: use an int w/_mm_cvtsi32_si128
      highbd_quantize_intrin_sse2: quiet int sanitizer warnings
      webmdec,WebmInputContext: make timestamp_ns signed
      vp8,VP8_COMP: normalize segment_encode_breakout type
      vpx_encoder.h: make flag constants unsigned
      loopfilter.c: normalize flat func param type
      update_thresh_freq_fact_row_mt: normalize param types
      vp9,search_new_mv: descale rather than scale sse
      compiler_attributes.h: add VPX_NO_UNSIGNED_SHIFT_CHECK
      use VPX_NO_UNSIGNED_SHIFT_CHECK with entropy functions
      vp9.read_inter_block_mode_info: return on corruption
      highbd_quantize_neon.c: remove unneeded assert.h
      vp9_ratectrl_rtc_test: initialize loopfilter_ctrl[]
      vp8_ratectrl_rtc_test.cc: ensure frame_type is initialized
      libs.doxy_template: remove obsolete CLASS_DIAGRAMS
      vpx_encoder.h: note VPX_ERROR_RESILIENT_PARTITIONS is VP8-only
      highbd_variance_neon,cosmetics: reorder a few lines
      test/*,cosmetics: normalize void parameter lists
      neon,load_unaligned_*: use dup for lane 0
      vpx_dsp,neon: simplify __ARM_FEATURE_DOTPROD check
      x86,cosmetics: prefer _mm_setzero_si128/_mm256_setzero_si256
      variance_neon.cc: simplify __ARM_FEATURE_DOTPROD check
      sad_neon: enable UDOT implementation w/aarch32
      vp8_decode: declare 2 variables volatile
      CHECK_MEM_ERROR: add an assert for a valid jmp target
      highbd_sad_avx2: normalize function param names
      vp9_highbd_quantize_fp*_neon: normalize fn param name
      SAD*Test: mark virtual Run() as overridden
      build: replace egrep with grep -E
      */Android.mk: add a check for NDK_ROOT

Jerome Jiang (10):
      Restore backward compatibility
      Add vp8_ prefix for quantize_lsx.c
      ABI compatibility to CHANGELOG for prev releases.
      Fix bug with smaller width bigger size
      Remove references to deprecated NumPy type aliases
      Add codec control to set per frame QP
      Skip calculating internal stats when frame dropped
      Update CHANGELOG
      Fix per frame qp for temporal layers
      Update AUTHORS .mailmap and version

Johann (12):
      fwd_txfm: remove avx2 file from non-hbd
      quantize: test lowbd in highbd builds
      quantize: increase iscan by 1
      quantize: add untested function
      quantize: standardize vp9_quantize_fp_sse2
      vp9 quantize: change index
      vp9 quantize: rewrite ssse3 in intrinsics
      quantize: consolidate sse2 conditionals
      mailmap: add johann@duck.com
      rtcd: allow disabling neon on armv8
      MacOS 13 is darwin22
      quantize: remove vp9_regular_quantize_b_4x4

Jonathan Wright (4):
      Use lane-referencing intrinsics in Neon convolution kernels
      Use Neon load/store helper functions consistently
      Implement horizontal convolutions using Neon USDOT instruction
      Implement vertical convolutions using Neon USDOT instruction

Konstantinos Margaritis (18):
      Revert "Revert "[NEON] Optimize vp9_diamond_search_sad() for NEON""
      Actually include the fix for commit 8f4d1890c.
      Provide Arm SDOT optimizations for SAD functions
      [NEON] Added vpx_highbd_quantize_b* functions
      [NEON] Added vpx_highbd_sad* functions
      [NEON] Add vpx_highbd_subtract_block function
      [NEON] Improve vpx_quantize_b* functions
      [NEON] Add highbd *variance* functions
      [NEON] highbd partial DCT functions
      [NEON] move transpose_8x8 to reuse
      [NEON] Move helper functions for reuse
      [NEON] Add highbd FDCT 4x4 function
      [NEON] Add highbd FDCT 8x8 function
      [NEON] Add highbd FDCT 16x16 function
      [NEON] fix clang compile warnings
      [NEON] Optimize and homogenize Butterfly DCT functions
      [NEON] Optimize highbd 32x32 DCT
      [NEON] Optimize FHT functions, add highbd FHT 4x4

Marco Paniconi (10):
      rtc-svc: Fix to make SVC work for Profile 1
      rtc: Add svc test for profile 2 10/12 bit
      Fix to VP8 external RC for dynamic update of layers
      Fix to VP8 external RC for buffer levels
      vp9-rc: Fix key frame setting in external RC
      vp9-svc: Fixes to make SVC work with VBR
      rc-rtc: Remove frame_flags_ change in svc ratectril rtc test
      rc-rtc: Test for periodic key in SVC external RC
      rc-svc: Add tests for dynamic svc in external RC
      Fix to segfault for external resize test in vp9

Mikko Koivisto (1):
      vp9: fix ubsan sub-overflows

Salome Thirot (5):
      Refactor Neon implementation of variance functions
      Refactor Neon subpel variance functions
      Specialize Neon subpel variance by filter value for large blocks
      Refactor Neon averaging subpel variance functions
      Specialize Neon averaging subpel variance by filter value

Sam James (1):
      build: fix -Wimplicit-int (Clang 16)

Scott LaVarnway (36):
      VPX: Add quantize speed test for ref vs opt.
      VPX: Add vpx_quantize_b_avx2().
      VPX: Add vpx_quantize_b_32x32_avx2().
      VPX: Add vpx_highbd_quantize_b_avx2().
      VPX: Add vpx_highbd_quantize_b_32x32_avx2().
      VPX: vp9_quantize_fp_avx2() cleanup.
      VPX: Add vp9_quantize_fp_32x32_avx2().
      VPX: Add vp9_highbd_quantize_fp_avx2().
      VPX: Add vp9_highbd_quantize_fp_32x32_avx2().
      VPX: Add vpx_subtract_block_avx2().
      VPX: Fix vp9_quantize_fp_avx2() VS build error.
      VPX: vp9_quantize_fp_neon() cleanup.
      VPX: Add vp9_highbd_quantize_fp_neon().
      vp9_quantize_fp_32x32_neon() cleanup.
      Add vp9_highbd_quantize_fp_32x32_neon().
      Fix TEST_P(SADx4Test, DISABLED_Speed)
      Add vpx_highbd_sad16x{32,16,8}x4d_avx2.
      Add vpx_highbd_sad32x{64,32,16}x4d_avx2.
      Add vpx_highbd_sad64x{64,32}x4d_avx2.
      post_proc_sse2.c: quiet -Wuninitialized
      resize_test.cc: quiet -Wmaybe-uninitialized
      vp9_rd.c quiet -Wstringop-overflow
      vpx_subpixel_8t_intrin_avx2.c: quiet -Wuninitialized
      Add vpx_highbd_sad16x{32,16,8}_avx2.
      Add vpx_highbd_sad32x{64,32,16}_avx2.
      Add vpx_highbd_sad64x{64,32}_avx2.
      SADavgTest: Add speed test.
      Add vpx_highbd_sad16x{32,16,8}_avg_avx2.
      Add vpx_highbd_sad32x{64,32,16}_avg_avx2.
      Add vpx_highbd_sad64x{64,32}_avg_avx2.
      Add vpx highbd subtract test.
      [x86]: Add vpx_highbd_subtract_block_avx2().
      Add vpx_highbd_comp_avg_pred_c() test.
      [x86]: Add vpx_highbd_comp_avg_pred_sse2().
      variance_test.cc: Enable VpxHBDMseTest for C and SSE2.
      variance_test.cc: Enable HBDMse speed test.

Wan-Teh Chang (3):
      Convert EncoderTest::last_pts_ to a local variable
      Fix off-by-one error of max w/h in validate_config
      Update third_party/googletest to v1.12.1

Yaowu Xu (1):
      Remove const for pass-by-value parameters

clang-format (1):
      .clang-format: update to clang-format-11